version: '3.1'
services:
  web:
    image: odoo:17.0
    depends_on:
      - odoodb
    ports:
      - "8069:8069"
    environment:
    - HOST=odoodb
    - USER=odoo
    - PASSWORD=odoodbpassword
  odoodb:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoodbpassword
      - POSTGRES_USER=odoo