version: '3'
services:
  database:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - db.env
    volumes:
      - mysql-data:/var/lib/mysql # persist data even if container shuts down
    ports: 
      - 3306:3306
  phpmyadmin:
    depends_on:
      - database
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: passwordroot
volumes:
  mysql-data: # named volumes can be managed easier using docker-compose
